# Generated by Django 4.1.5 on 2023-02-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('correct_answers', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('seconds', models.IntegerField()),
            ],
        ),
    ]
